# Generated by Django 4.1.3 on 2022-12-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('good_article', models.IntegerField(verbose_name='Артикул')),
                ('goods_plu', models.IntegerField(verbose_name='PLU')),
                ('goods_constituent', models.CharField(max_length=100, verbose_name='Состав')),
                ('goods_conditions', models.CharField(max_length=200, verbose_name='Условия хранения')),
                ('goods_period', models.IntegerField(verbose_name='Срок хранения')),
                ('goods_nutrition', models.CharField(max_length=200, verbose_name='Пищевая ценность')),
                ('goods_weight', models.IntegerField(verbose_name='Масса')),
                ('goods_text', models.CharField(max_length=100, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'номенклатуру',
                'verbose_name_plural': 'номенклатура',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50, verbose_name='Организация')),
                ('org_address', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'организацию',
                'verbose_name_plural': 'организация',
            },
        ),
    ]
