# Generated by Django 4.1.3 on 2022-11-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'организацию', 'verbose_name_plural': 'организация'},
        ),
    ]
