# Generated by Django 4.1.3 on 2022-11-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_organisation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'номенклатуру', 'verbose_name_plural': 'номенклатура'},
        ),
    ]
