# Generated by Django 4.1.3 on 2022-11-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_goods_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_nutrition',
            field=models.CharField(default='-', max_length=200, verbose_name='Пищевая ценность'),
            preserve_default=False,
        ),
    ]
