# Generated by Django 4.1.3 on 2022-11-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_goods_goods_nutrition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_temperature',
        ),
    ]
